name: Dependabot Summary Reusable Workflow

on:
  workflow_call:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bismayam/Dependabot-Security-Summary
          path: Dependabot-Security-Summary   # checkout into a subfolder

      - name: Run Dependabot Summary Script
        run: bash Dependabot-Security-Summary/.github/scripts/fetch-dependabot-alerts.sh
        env:
          PAT_TOKEN: ${{ secrets.DEPENDABOT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_TOKEN: ${{ secrets.TEST }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

