name: Dependabot Summary Reusable Workflow

on:
  workflow_call:
    inputs:
      DEPENDABOT:
        description: "Personal Access Token for Dependabot"
        required: true
        type: string

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: bismayam/Dependabot-Security-Summary
          path: Dependabot-Security-Summary

      - name: Run Dependabot Summary Script
        run: bash Dependabot-Security-Summary/.github/scripts/fetch-dependabot-alerts.sh
        env:
          PAT_TOKEN: ${{ inputs.DEPENDABOT }}      # <-- now passed as input
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
